<?php
declare(strict_types=1);
namespace Tests\Integration\Financial;
use Tests\Support\ResetsConfiguredRedis;
use App\Contracts\WalletServiceInterface;use App\Services\EscrowService;use Core\Container;use Core\Database;use PHPUnit\Framework\TestCase;
/**
 * @runTestsInSeparateProcesses
 * @preserveGlobalState disabled
 */
final class EscrowDisputeSplitInvariantTest extends TestCase{
    use ResetsConfiguredRedis;private Database $db;private WalletServiceInterface $wallet;private EscrowService $escrow;private int $buyer=1;private int $seller=2;private int $ob;protected function setUp():void{parent::setUp();ini_set('error_log', sys_get_temp_dir() . '/chortke-financial-integration.log');config_set('app.key', 'testing-app-key-32-characters-long!!');$this->ob=ob_get_level();ob_start();try{$c=Container::getInstance();$this->db=$c->make(Database::class);$this->wallet=$c->make(WalletServiceInterface::class);$this->escrow=$c->make(EscrowService::class);$this->db->getPdo();$this->db->query("DELETE FROM score_events WHERE entity_type='user' AND domain='fraud' AND entity_id IN (1,2,3,4)");$this->db->query("UPDATE users SET fraud_score=0,is_blacklisted=0,status='active' WHERE id IN (1,2,3,4)");$this->db->query("UPDATE user_scores SET score=0 WHERE domain='fraud' AND user_id IN (1,2,3,4)");$this->resetConfiguredRedis([1,2,3,4]);}catch(\Throwable $e){$this->fail('Financial DB unavailable: '.$e->getMessage());}$this->db->beginTransaction();foreach([[$this->buyer,'50000000.0000'],[$this->seller,'0.0000']]as[$id,$b])$this->db->query('INSERT INTO wallets (user_id, balance_irt, locked_irt, is_frozen) VALUES (?, ?, 0, 0) ON DUPLICATE KEY UPDATE balance_irt = VALUES(balance_irt), locked_irt = 0, is_frozen = 0',[$id,$b]);}protected function tearDown():void{if(isset($this->db)&&$this->db->inTransaction())$this->db->rollback();while(isset($this->ob)&&ob_get_level()>$this->ob)ob_end_clean();parent::tearDown();}
/** @test */public function split_dispute_refunds_buyer_and_pays_seller_atomically():void{$id=$this->fundedDisputedEscrow('20000.0000');$r=$this->escrow->resolveDisputePartial($id,$this->buyer,$this->seller,'5000.0000','15000.0000','admin','split','test-split-'.bin2hex(random_bytes(8)));$this->assertTrue((bool)($r['ok']??false),(json_encode($r) ?: ''));$b=$this->row($this->buyer);$s=$this->row($this->seller);$this->assertSame('49985000.00000000',(string)$b->balance_irt);$this->assertSame('0.00000000',(string)$b->locked_irt);$this->assertSame('15000.00000000',(string)$s->balance_irt);$e=$this->db->fetch('SELECT status,amount,partial_released FROM escrow_transactions WHERE id=?',[$id]);$this->assertInstanceOf(\stdClass::class,$e);$this->assertSame('released',(string)$e->status);$this->assertSame('0.00000000',(string)$e->amount);$this->assertSame('15000.00000000',(string)$e->partial_released);}
private function fundedDisputedEscrow(string $a):int{$order=random_int(100000000,999999999);$h=$this->wallet->withdraw($this->buyer,$a,'irt',['type'=>'custom_deal_escrow','order_id'=>$order,'ref_id'=>$order,'ref_type'=>'custom_deal','idempotency_key'=>'hold-'.bin2hex(random_bytes(8))]);$this->assertTrue((bool)($h['success']??false));$this->db->query("INSERT INTO escrow_transactions (order_id,order_type,buyer_id,seller_id,amount,currency,status,held_at,expires_at) VALUES (?, 'custom_deal', ?, ?, ?, 'irt','disputed',NOW(),DATE_ADD(NOW(),INTERVAL 1 DAY))",[$order,$this->buyer,$this->seller,$a]);return(int)$this->db->lastInsertId();}private function row(int$id):\stdClass{$r=$this->db->fetch('SELECT balance_irt,locked_irt FROM wallets WHERE user_id=? FOR UPDATE',[$id]);$this->assertInstanceOf(\stdClass::class,$r);return$r;}}
