SET FOREIGN_KEY_CHECKS = 0;

-- Wave 3 schema compatibility after reset
ALTER TABLE `lottery_rounds`
  ADD COLUMN IF NOT EXISTS `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `start_date` TIMESTAMP NULL,
  ADD COLUMN IF NOT EXISTS `end_date` TIMESTAMP NULL,
  ADD COLUMN IF NOT EXISTS `prize_amount` DECIMAL(24,4) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `ticket_price` DECIMAL(24,4) DEFAULT 5000,
  ADD COLUMN IF NOT EXISTS `max_capacity` INT(10) UNSIGNED DEFAULT 1000,
  ADD COLUMN IF NOT EXISTS `currency` VARCHAR(10) NOT NULL DEFAULT 'irt',
  ADD COLUMN IF NOT EXISTS `entry_fee` DECIMAL(24,4) NULL;

ALTER TABLE `lottery_participations`
  ADD COLUMN IF NOT EXISTS `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `status` VARCHAR(50) DEFAULT 'active',
  ADD COLUMN IF NOT EXISTS `chance_score` DECIMAL(24,4) DEFAULT 100,
  ADD COLUMN IF NOT EXISTS `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `lottery_daily_numbers`
  ADD COLUMN IF NOT EXISTS `round_id` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `number1` INT NULL,
  ADD COLUMN IF NOT EXISTS `number2` INT NULL,
  ADD COLUMN IF NOT EXISTS `number3` INT NULL,
  ADD COLUMN IF NOT EXISTS `selected_number` INT NULL,
  ADD COLUMN IF NOT EXISTS `status` VARCHAR(50) NOT NULL DEFAULT 'pending',
  ADD COLUMN IF NOT EXISTS `seed_hash` VARCHAR(128) NULL,
  ADD COLUMN IF NOT EXISTS `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `lottery_votes`
  ADD COLUMN IF NOT EXISTS `daily_number_id` INT(10) UNSIGNED NULL,
  ADD COLUMN IF NOT EXISTS `participation_id` INT(10) UNSIGNED NULL,
  ADD COLUMN IF NOT EXISTS `status` VARCHAR(50) NOT NULL DEFAULT 'cast',
  ADD COLUMN IF NOT EXISTS `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `prediction_games`
  ADD COLUMN IF NOT EXISTS `team_home` VARCHAR(100) NULL,
  ADD COLUMN IF NOT EXISTS `team_away` VARCHAR(100) NULL,
  ADD COLUMN IF NOT EXISTS `sport_type` VARCHAR(50) DEFAULT 'football',
  ADD COLUMN IF NOT EXISTS `deleted_at` TIMESTAMP NULL,
  ADD COLUMN IF NOT EXISTS `bet_deadline` TIMESTAMP NULL,
  ADD COLUMN IF NOT EXISTS `match_date` TIMESTAMP NULL,
  ADD COLUMN IF NOT EXISTS `min_bet_usdt` DECIMAL(24,4) DEFAULT 1,
  ADD COLUMN IF NOT EXISTS `max_bet_usdt` DECIMAL(24,4) DEFAULT 1000,
  ADD COLUMN IF NOT EXISTS `commission_percent` DECIMAL(5,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `cancelled_at` TIMESTAMP NULL,
  ADD COLUMN IF NOT EXISTS `cancelled_by` INT(10) UNSIGNED NULL,
  ADD COLUMN IF NOT EXISTS `paid_at` TIMESTAMP NULL,
  ADD COLUMN IF NOT EXISTS `finished_at` TIMESTAMP NULL,
  ADD COLUMN IF NOT EXISTS `settled_by` INT(10) UNSIGNED NULL,
  ADD COLUMN IF NOT EXISTS `winners_paid` TINYINT(1) NOT NULL DEFAULT 0;

ALTER TABLE `prediction_bets`
  ADD COLUMN IF NOT EXISTS `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `amount_usdt` DECIMAL(24,4) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `payout_usdt` DECIMAL(24,4) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `settled_at` TIMESTAMP NULL,
  ADD COLUMN IF NOT EXISTS `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE `influencer_profiles`
  ADD COLUMN IF NOT EXISTS `follower_count` INT(10) UNSIGNED DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `page_url` VARCHAR(2048) NULL,
  ADD COLUMN IF NOT EXISTS `profile_image` VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS `engagement_rate` DECIMAL(5,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `category` VARCHAR(100) NULL,
  ADD COLUMN IF NOT EXISTS `bio` TEXT NULL,
  ADD COLUMN IF NOT EXISTS `story_price_24h` DECIMAL(24,4) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `post_price_24h` DECIMAL(24,4) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `post_price_48h` DECIMAL(24,4) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `post_price_72h` DECIMAL(24,4) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `currency` VARCHAR(10) DEFAULT 'irt',
  ADD COLUMN IF NOT EXISTS `total_orders` INT(10) UNSIGNED DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `completed_orders` INT(10) UNSIGNED DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `average_rating` DECIMAL(3,2) DEFAULT 5,
  ADD COLUMN IF NOT EXISTS `verification_code` VARCHAR(50) NULL,
  ADD COLUMN IF NOT EXISTS `verification_post_url` VARCHAR(2048) NULL,
  ADD COLUMN IF NOT EXISTS `rejection_reason` TEXT NULL,
  ADD COLUMN IF NOT EXISTS `verified_by` INT(10) UNSIGNED NULL,
  ADD COLUMN IF NOT EXISTS `verified_at` TIMESTAMP NULL,
  ADD COLUMN IF NOT EXISTS `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS `priority` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `deleted_at` TIMESTAMP NULL;

ALTER TABLE `story_orders`
  ADD COLUMN IF NOT EXISTS `order_type` VARCHAR(50) DEFAULT 'story',
  ADD COLUMN IF NOT EXISTS `duration_hours` INT(10) UNSIGNED DEFAULT 24,
  ADD COLUMN IF NOT EXISTS `caption` TEXT NULL,
  ADD COLUMN IF NOT EXISTS `link` VARCHAR(2048) NULL,
  ADD COLUMN IF NOT EXISTS `preferred_publish_time` DATETIME NULL,
  ADD COLUMN IF NOT EXISTS `site_fee_percent` DECIMAL(5,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `site_fee_amount` DECIMAL(24,4) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `influencer_earning` DECIMAL(24,4) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `payment_transaction_id` VARCHAR(128) NULL,
  ADD COLUMN IF NOT EXISTS `payout_transaction_id` VARCHAR(128) NULL,
  ADD COLUMN IF NOT EXISTS `proof_link` VARCHAR(2048) NULL,
  ADD COLUMN IF NOT EXISTS `proof_notes` TEXT NULL,
  ADD COLUMN IF NOT EXISTS `proof_submitted_at` TIMESTAMP NULL,
  ADD COLUMN IF NOT EXISTS `buyer_confirmed_at` TIMESTAMP NULL,
  ADD COLUMN IF NOT EXISTS `buyer_check_deadline` TIMESTAMP NULL,
  ADD COLUMN IF NOT EXISTS `peer_resolution_started_at` TIMESTAMP NULL,
  ADD COLUMN IF NOT EXISTS `rejection_reason` TEXT NULL,
  ADD COLUMN IF NOT EXISTS `admin_note` TEXT NULL,
  ADD COLUMN IF NOT EXISTS `metadata` LONGTEXT NULL;

SET FOREIGN_KEY_CHECKS = 1;
