SET FOREIGN_KEY_CHECKS = 0;

-- Wave 4 KYC / Investment / Escrow schema compatibility

ALTER TABLE `kyc_verifications`
  MODIFY COLUMN `national_code` TEXT NULL,
  MODIFY COLUMN `birth_date` VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS `first_name` VARCHAR(100) NULL,
  ADD COLUMN IF NOT EXISTS `last_name` VARCHAR(100) NULL,
  ADD COLUMN IF NOT EXISTS `national_code_hash` VARCHAR(128) NULL,
  ADD COLUMN IF NOT EXISTS `front_image` VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS `back_image` VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS `selfie_image` VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS `under_review_by` INT(10) UNSIGNED NULL,
  ADD COLUMN IF NOT EXISTS `review_started_at` TIMESTAMP NULL,
  ADD COLUMN IF NOT EXISTS `reviewed_by` INT(10) UNSIGNED NULL,
  ADD COLUMN IF NOT EXISTS `admin_note` TEXT NULL;

ALTER TABLE `investments`
  ADD COLUMN IF NOT EXISTS `deleted_at` TIMESTAMP NULL DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `current_balance` DECIMAL(24,8) NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `last_profit_date` TIMESTAMP NULL DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  ADD COLUMN IF NOT EXISTS `transaction_id` VARCHAR(64) NULL,
  ADD COLUMN IF NOT EXISTS `total_profit` DECIMAL(24,8) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `total_loss` DECIMAL(24,8) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `last_withdrawal_date` DATETIME NULL,
  ADD COLUMN IF NOT EXISTS `deposit_lock_until` DATETIME NULL,
  ADD COLUMN IF NOT EXISTS `start_date` DATETIME NULL;

UPDATE `investments` SET `current_balance` = COALESCE(NULLIF(`current_balance`,0), `amount`) WHERE `current_balance` IS NULL OR `current_balance` = 0;

ALTER TABLE `investment_withdrawals`
  ADD COLUMN IF NOT EXISTS `user_id` INT(10) UNSIGNED NULL,
  ADD COLUMN IF NOT EXISTS `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `type` VARCHAR(30) DEFAULT 'profit_only',
  ADD COLUMN IF NOT EXISTS `request_id` VARCHAR(100) NULL,
  ADD COLUMN IF NOT EXISTS `rejection_reason` TEXT NULL,
  ADD COLUMN IF NOT EXISTS `processed_at` DATETIME NULL,
  ADD COLUMN IF NOT EXISTS `processed_by` INT(10) UNSIGNED NULL,
  ADD COLUMN IF NOT EXISTS `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

CREATE TABLE IF NOT EXISTS `investment_profits` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `investment_id` INT(10) UNSIGNED NOT NULL,
  `user_id` INT(10) UNSIGNED NULL,
  `amount` DECIMAL(24,8) NOT NULL DEFAULT 0,
  `currency` VARCHAR(10) DEFAULT 'usdt',
  `profit_type` VARCHAR(20) DEFAULT NULL,
  `status` VARCHAR(20) DEFAULT 'paid',
  `transaction_id` VARCHAR(64) DEFAULT NULL,
  `period_date` DATE DEFAULT NULL,
  `net_amount` DECIMAL(24,8) DEFAULT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `escrow_logs` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `escrow_id` INT(10) UNSIGNED NOT NULL,
  `action` VARCHAR(100) NOT NULL,
  `actor_id` INT(10) UNSIGNED NULL,
  `actor_type` VARCHAR(50) NULL,
  `details` LONGTEXT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_escrow_logs_escrow` (`escrow_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

ALTER TABLE `escrow_transactions`
  ADD COLUMN IF NOT EXISTS `transaction_id` VARCHAR(64) NULL,
  ADD COLUMN IF NOT EXISTS `metadata` LONGTEXT NULL;

SET FOREIGN_KEY_CHECKS = 1;
