-- CHORTKE MIGRATION PART 36: REALTIME & RATE LIMITING
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `rate_limit_requests`;
CREATE TABLE `rate_limit_requests` (
  `id` INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `identifier_key` VARCHAR(191) NOT NULL,
  `action` VARCHAR(100) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `rate_limit_whitelist`;
CREATE TABLE `rate_limit_whitelist` (
  `id` INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `identifier` VARCHAR(191) NOT NULL,
  `identifier_type` VARCHAR(30) NOT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `expires_at` TIMESTAMP NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `realtime_messages`;
CREATE TABLE `realtime_messages` (
  `id` INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `room` VARCHAR(100) DEFAULT NULL,
  `user_id` INT(10) UNSIGNED DEFAULT NULL,
  `type` VARCHAR(100) NOT NULL,
  `payload` JSON NOT NULL,
  `is_read` TINYINT(1) DEFAULT 0,
  `expires_at` TIMESTAMP NOT NULL,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `queues`;
CREATE TABLE `queues` (
  `id` INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `queue` VARCHAR(255) NOT NULL DEFAULT 'default',
  `payload` LONGTEXT NOT NULL,
  `attempts` TINYINT(3) UNSIGNED NOT NULL DEFAULT 0,
  `reserved_at` TIMESTAMP NULL DEFAULT NULL,
  `available_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET FOREIGN_KEY_CHECKS = 1;
