-- Content phase 1: schema compatibility for content submissions/revenues/agreement

ALTER TABLE `content_submissions`
  ADD COLUMN IF NOT EXISTS `video_url` VARCHAR(500) NULL DEFAULT NULL AFTER `platform`,
  ADD COLUMN IF NOT EXISTS `description` TEXT NULL DEFAULT NULL AFTER `title`,
  ADD COLUMN IF NOT EXISTS `category` VARCHAR(100) NULL DEFAULT NULL AFTER `description`,
  ADD COLUMN IF NOT EXISTS `agreement_accepted` TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `agreement_accepted_at` TIMESTAMP NULL DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `agreement_ip` VARCHAR(45) NULL DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `agreement_fingerprint` VARCHAR(128) NULL DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `approved_at` TIMESTAMP NULL DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `approved_by` INT(10) UNSIGNED NULL DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `reviewed_by` INT(10) UNSIGNED NULL DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `reviewed_at` TIMESTAMP NULL DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `rejection_reason` TEXT NULL DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `rejected_by` INT(10) UNSIGNED NULL DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `rejected_at` TIMESTAMP NULL DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `published_at` TIMESTAMP NULL DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `published_url` VARCHAR(500) NULL DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `published_by` INT(10) UNSIGNED NULL DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `channel_name` VARCHAR(255) NULL DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `suspended_at` TIMESTAMP NULL DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `suspended_by` INT(10) UNSIGNED NULL DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `admin_notes` TEXT NULL DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

UPDATE `content_submissions` SET `video_url` = COALESCE(`video_url`, `url`) WHERE `video_url` IS NULL AND `url` IS NOT NULL;

ALTER TABLE `content_agreements`
  MODIFY COLUMN `content_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `submission_id` INT(10) UNSIGNED NULL DEFAULT NULL AFTER `content_id`,
  ADD COLUMN IF NOT EXISTS `agreement_text` TEXT NULL DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `accepted_at` TIMESTAMP NULL DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `ip_address` VARCHAR(45) NULL DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `user_agent` VARCHAR(500) NULL DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `device_fingerprint` VARCHAR(128) NULL DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

UPDATE `content_agreements` SET `submission_id` = COALESCE(`submission_id`, `content_id`) WHERE `submission_id` IS NULL;
UPDATE `content_agreements` SET `accepted_at` = COALESCE(`accepted_at`, `agreed_at`) WHERE `accepted_at` IS NULL;

ALTER TABLE `content_revenues`
  MODIFY COLUMN `content_id` INT(10) UNSIGNED NULL DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `submission_id` INT(10) UNSIGNED NULL DEFAULT NULL AFTER `content_id`,
  ADD COLUMN IF NOT EXISTS `period` VARCHAR(20) NULL DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `views` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `total_revenue` DECIMAL(24,8) NOT NULL DEFAULT 0.00000000,
  ADD COLUMN IF NOT EXISTS `gross_amount` DECIMAL(24,8) NOT NULL DEFAULT 0.00000000,
  ADD COLUMN IF NOT EXISTS `site_share_percent` DECIMAL(6,2) NOT NULL DEFAULT 0.00,
  ADD COLUMN IF NOT EXISTS `site_share_amount` DECIMAL(24,8) NOT NULL DEFAULT 0.00000000,
  ADD COLUMN IF NOT EXISTS `platform_fee` DECIMAL(24,8) NOT NULL DEFAULT 0.00000000,
  ADD COLUMN IF NOT EXISTS `user_share_percent` DECIMAL(6,2) NOT NULL DEFAULT 0.00,
  ADD COLUMN IF NOT EXISTS `user_share_amount` DECIMAL(24,8) NOT NULL DEFAULT 0.00000000,
  ADD COLUMN IF NOT EXISTS `tax_percent` DECIMAL(6,2) NOT NULL DEFAULT 0.00,
  ADD COLUMN IF NOT EXISTS `tax_amount` DECIMAL(24,8) NOT NULL DEFAULT 0.00000000,
  ADD COLUMN IF NOT EXISTS `net_user_amount` DECIMAL(24,8) NOT NULL DEFAULT 0.00000000,
  ADD COLUMN IF NOT EXISTS `currency` VARCHAR(10) NOT NULL DEFAULT 'irt',
  ADD COLUMN IF NOT EXISTS `metadata` LONGTEXT NULL DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `reviewed_by` INT(10) UNSIGNED NULL DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `reviewed_at` TIMESTAMP NULL DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `paid_at` TIMESTAMP NULL DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `paid_by_admin` INT(10) UNSIGNED NULL DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `transaction_id` VARCHAR(100) NULL DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `admin_notes` TEXT NULL DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `created_by` INT(10) UNSIGNED NULL DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `is_deleted` TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `updated_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

UPDATE `content_revenues` SET `submission_id` = COALESCE(`submission_id`, `content_id`) WHERE `submission_id` IS NULL;
UPDATE `content_revenues` SET `total_revenue` = COALESCE(NULLIF(`total_revenue`,0), `amount`, 0) WHERE `amount` IS NOT NULL;
UPDATE `content_revenues` SET `gross_amount` = COALESCE(NULLIF(`gross_amount`,0), `total_revenue`, `amount`, 0);
UPDATE `content_revenues` SET `net_user_amount` = COALESCE(NULLIF(`net_user_amount`,0), `amount`, 0) WHERE `amount` IS NOT NULL;

CREATE INDEX IF NOT EXISTS `idx_content_submissions_user_status` ON `content_submissions` (`user_id`, `status`, `is_deleted`);
CREATE INDEX IF NOT EXISTS `idx_content_revenues_user_status` ON `content_revenues` (`user_id`, `status`, `is_deleted`);
CREATE INDEX IF NOT EXISTS `idx_content_revenues_submission_period` ON `content_revenues` (`submission_id`, `period`);
