SET FOREIGN_KEY_CHECKS = 0;

-- =============================================================================
-- CURRENCY-UNIT-2026-06 — Normalize all currency columns to IRT (تومان).
-- =============================================================================
--
-- The platform's official unit is Toman (IRT). Rial (IRR) appears ONLY at the
-- payment-gateway adapter boundary (DgPay/IDPay/NextPay convert Toman to Rial
-- when calling the bank API, and back to Toman immediately on return).
--
-- This migration backfills any historic rows that stored 'irr'/'rial' as a
-- currency code to 'irt'. The PHP code now defaults to IRT
-- (see core/ValueObjects/Money.php::DEFAULT_CURRENCY).
--
-- The table list below was generated by:
--   SELECT TABLE_NAME, COLUMN_NAME FROM information_schema.COLUMNS
--   WHERE TABLE_SCHEMA = DATABASE()
--     AND COLUMN_NAME IN ('currency','reward_currency','penalty_currency');
-- =============================================================================

-- ── Wallet / financial movement ───────────────────────────────────────────────
UPDATE transactions             SET currency = 'irt' WHERE LOWER(currency) IN ('irr','rial');
UPDATE transactions_archive     SET currency = 'irt' WHERE LOWER(currency) IN ('irr','rial');
UPDATE withdrawals              SET currency = 'irt' WHERE LOWER(currency) IN ('irr','rial');
UPDATE manual_deposits          SET currency = 'irt' WHERE LOWER(currency) IN ('irr','rial');
UPDATE crypto_deposits          SET currency = 'irt' WHERE LOWER(currency) IN ('irr','rial');
UPDATE crypto_deposit_intents   SET currency = 'irt' WHERE LOWER(currency) IN ('irr','rial');
UPDATE ledger_entries           SET currency = 'irt' WHERE LOWER(currency) IN ('irr','rial');
UPDATE scheduled_payments       SET currency = 'irt' WHERE LOWER(currency) IN ('irr','rial');

-- ── Tasks ─────────────────────────────────────────────────────────────────────
UPDATE custom_task_submissions  SET reward_currency  = 'irt' WHERE LOWER(reward_currency)  IN ('irr','rial');
UPDATE social_task_executions   SET reward_currency  = 'irt' WHERE LOWER(reward_currency)  IN ('irr','rial');
UPDATE task_executions          SET reward_currency  = 'irt' WHERE LOWER(reward_currency)  IN ('irr','rial');
UPDATE task_rechecks            SET penalty_currency = 'irt' WHERE LOWER(penalty_currency) IN ('irr','rial');

-- ── Other monetary records ────────────────────────────────────────────────────
UPDATE escrows                  SET currency = 'irt' WHERE LOWER(currency) IN ('irr','rial');
UPDATE escrow_transactions      SET currency = 'irt' WHERE LOWER(currency) IN ('irr','rial');
UPDATE prediction_bets          SET currency = 'irt' WHERE LOWER(currency) IN ('irr','rial');
UPDATE referral_commissions     SET currency = 'irt' WHERE LOWER(currency) IN ('irr','rial');
UPDATE referral_milestones      SET currency = 'irt' WHERE LOWER(currency) IN ('irr','rial');
UPDATE story_orders             SET currency = 'irt' WHERE LOWER(currency) IN ('irr','rial');
UPDATE user_level_purchases     SET currency = 'irt' WHERE LOWER(currency) IN ('irr','rial');
UPDATE vitrine_listings         SET currency = 'irt' WHERE LOWER(currency) IN ('irr','rial');
UPDATE seo_keywords             SET currency = 'irt' WHERE LOWER(currency) IN ('irr','rial');

-- ── User preferences (uppercase IRT for backward-compatible reads) ────────────
UPDATE user_settings
   SET setting_value = 'IRT'
 WHERE setting_key   = 'currency'
   AND UPPER(setting_value) IN ('IRR','RIAL');

SET FOREIGN_KEY_CHECKS = 1;
