SET FOREIGN_KEY_CHECKS = 0;

-- SocialTask schema reconciliation for ST-01..ST-14

ALTER TABLE `ads`
  MODIFY COLUMN `type` VARCHAR(50) NOT NULL,
  ADD COLUMN IF NOT EXISTS `link` VARCHAR(2048) NULL,
  ADD COLUMN IF NOT EXISTS `target_url` VARCHAR(2048) NULL,
  ADD COLUMN IF NOT EXISTS `currency` VARCHAR(10) DEFAULT 'irt',
  ADD COLUMN IF NOT EXISTS `site_commission_percent` DECIMAL(5,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `created_by` INT(10) UNSIGNED NULL,
  ADD COLUMN IF NOT EXISTS `reject_reason` TEXT NULL,
  ADD COLUMN IF NOT EXISTS `reviewed_by` INT(10) UNSIGNED NULL,
  ADD COLUMN IF NOT EXISTS `reviewed_at` TIMESTAMP NULL,
  ADD COLUMN IF NOT EXISTS `site_url` VARCHAR(2048) NULL,
  ADD COLUMN IF NOT EXISTS `min_payout` DECIMAL(24,8) DEFAULT 0.00000000,
  ADD COLUMN IF NOT EXISTS `max_payout` DECIMAL(24,8) DEFAULT 0.00000000,
  ADD COLUMN IF NOT EXISTS `target_duration` INT(10) UNSIGNED DEFAULT 60,
  ADD COLUMN IF NOT EXISTS `min_score` INT(10) UNSIGNED DEFAULT 40,
  ADD COLUMN IF NOT EXISTS `max_per_day` INT(10) UNSIGNED DEFAULT 10,
  ADD COLUMN IF NOT EXISTS `executions_count` INT(10) UNSIGNED DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `budget` DECIMAL(24,8) DEFAULT 0.00000000;

ALTER TABLE `social_task_executions`
  MODIFY COLUMN `status` VARCHAR(50) DEFAULT 'pending',
  ADD COLUMN IF NOT EXISTS `ip_address` VARCHAR(45) NULL,
  ADD COLUMN IF NOT EXISTS `user_agent` TEXT NULL,
  ADD COLUMN IF NOT EXISTS `started_at` TIMESTAMP NULL,
  ADD COLUMN IF NOT EXISTS `expected_time` INT(10) UNSIGNED DEFAULT 60,
  ADD COLUMN IF NOT EXISTS `active_time` INT(10) UNSIGNED DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `task_score` INT(10) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `decision` VARCHAR(50) NULL,
  ADD COLUMN IF NOT EXISTS `behavior_data` LONGTEXT NULL,
  ADD COLUMN IF NOT EXISTS `flag_review` TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `flag_note` TEXT NULL,
  ADD COLUMN IF NOT EXISTS `anti_fraud_score` INT(10) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `reward_paid` TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `override_reason` TEXT NULL,
  ADD COLUMN IF NOT EXISTS `reviewed_by` INT(10) UNSIGNED NULL,
  ADD COLUMN IF NOT EXISTS `reject_reason` TEXT NULL;

CREATE INDEX IF NOT EXISTS `idx_ste_status_updated` ON `social_task_executions` (`status`, `updated_at`);
CREATE INDEX IF NOT EXISTS `idx_ste_executor_type_time` ON `social_task_executions` (`executor_id`, `created_at`);

ALTER TABLE `social_camera_requests`
  MODIFY COLUMN `status` VARCHAR(50) DEFAULT 'pending',
  ADD COLUMN IF NOT EXISTS `expires_at` TIMESTAMP NULL,
  ADD COLUMN IF NOT EXISTS `camera_score` INT(10) DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS `verified_signals` LONGTEXT NULL,
  ADD COLUMN IF NOT EXISTS `completed_at` TIMESTAMP NULL;

SET FOREIGN_KEY_CHECKS = 1;
