SET FOREIGN_KEY_CHECKS = 0;

-- Influencer marketplace schema reconciliation for INF-01..INF-15

ALTER TABLE `influencer_profiles`
  ADD COLUMN IF NOT EXISTS `follower_count` INT(10) UNSIGNED DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `page_url` VARCHAR(2048) NULL,
  ADD COLUMN IF NOT EXISTS `profile_image` VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS `engagement_rate` DECIMAL(5,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `category` VARCHAR(100) NULL,
  ADD COLUMN IF NOT EXISTS `bio` TEXT NULL,
  ADD COLUMN IF NOT EXISTS `story_price_24h` DECIMAL(24,4) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `post_price_24h` DECIMAL(24,4) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `post_price_48h` DECIMAL(24,4) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `post_price_72h` DECIMAL(24,4) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `currency` VARCHAR(10) DEFAULT 'irt',
  ADD COLUMN IF NOT EXISTS `total_orders` INT(10) UNSIGNED DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `completed_orders` INT(10) UNSIGNED DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `average_rating` DECIMAL(3,2) DEFAULT 5.00,
  ADD COLUMN IF NOT EXISTS `verification_code` VARCHAR(50) NULL,
  ADD COLUMN IF NOT EXISTS `verification_post_url` VARCHAR(2048) NULL,
  ADD COLUMN IF NOT EXISTS `rejection_reason` TEXT NULL,
  ADD COLUMN IF NOT EXISTS `verified_by` INT(10) UNSIGNED NULL,
  ADD COLUMN IF NOT EXISTS `verified_at` TIMESTAMP NULL,
  ADD COLUMN IF NOT EXISTS `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS `priority` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `suspended_at` TIMESTAMP NULL,
  ADD COLUMN IF NOT EXISTS `suspended_reason` TEXT NULL,
  ADD COLUMN IF NOT EXISTS `deleted_at` TIMESTAMP NULL DEFAULT NULL;

UPDATE `influencer_profiles`
SET `follower_count` = CASE WHEN COALESCE(`follower_count`,0)=0 THEN COALESCE(`followers_count`,0) ELSE `follower_count` END,
    `story_price_24h` = CASE WHEN COALESCE(`story_price_24h`,0)=0 THEN COALESCE(`price_story`,0) ELSE `story_price_24h` END;

ALTER TABLE `influencer_verifications`
  ADD COLUMN IF NOT EXISTS `profile_id` INT(10) UNSIGNED NULL AFTER `id`,
  ADD COLUMN IF NOT EXISTS `code` VARCHAR(80) NULL,
  ADD COLUMN IF NOT EXISTS `post_url` VARCHAR(2048) NULL,
  ADD COLUMN IF NOT EXISTS `expires_at` TIMESTAMP NULL,
  ADD COLUMN IF NOT EXISTS `submitted_at` TIMESTAMP NULL,
  ADD COLUMN IF NOT EXISTS `approved_at` TIMESTAMP NULL,
  ADD COLUMN IF NOT EXISTS `rejection_reason` TEXT NULL,
  ADD COLUMN IF NOT EXISTS `updated_at` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP;

UPDATE `influencer_verifications` SET `profile_id` = COALESCE(`profile_id`, `influencer_id`) WHERE `profile_id` IS NULL;
CREATE INDEX IF NOT EXISTS `idx_influencer_verifications_profile` ON `influencer_verifications` (`profile_id`);

ALTER TABLE `story_orders`
  ADD COLUMN IF NOT EXISTS `order_type` VARCHAR(50) DEFAULT 'story',
  ADD COLUMN IF NOT EXISTS `duration_hours` INT(10) UNSIGNED DEFAULT 24,
  ADD COLUMN IF NOT EXISTS `media_path` VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS `caption` TEXT NULL,
  ADD COLUMN IF NOT EXISTS `link` VARCHAR(2048) NULL,
  ADD COLUMN IF NOT EXISTS `preferred_publish_time` DATETIME NULL,
  ADD COLUMN IF NOT EXISTS `actual_publish_time` DATETIME NULL,
  ADD COLUMN IF NOT EXISTS `site_fee_percent` DECIMAL(5,2) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `site_fee_amount` DECIMAL(24,4) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `influencer_earning` DECIMAL(24,4) DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `payment_transaction_id` VARCHAR(128) NULL,
  ADD COLUMN IF NOT EXISTS `payout_transaction_id` VARCHAR(128) NULL,
  ADD COLUMN IF NOT EXISTS `proof_screenshot` VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS `proof_video` VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS `proof_link` VARCHAR(2048) NULL,
  ADD COLUMN IF NOT EXISTS `proof_notes` TEXT NULL,
  ADD COLUMN IF NOT EXISTS `proof_submitted_at` TIMESTAMP NULL,
  ADD COLUMN IF NOT EXISTS `buyer_check_notified_at` TIMESTAMP NULL,
  ADD COLUMN IF NOT EXISTS `buyer_confirmed_at` TIMESTAMP NULL,
  ADD COLUMN IF NOT EXISTS `buyer_check_deadline` TIMESTAMP NULL,
  ADD COLUMN IF NOT EXISTS `peer_resolution_started_at` TIMESTAMP NULL,
  ADD COLUMN IF NOT EXISTS `rejection_reason` TEXT NULL,
  ADD COLUMN IF NOT EXISTS `customer_rating` INT NULL,
  ADD COLUMN IF NOT EXISTS `customer_review` TEXT NULL,
  ADD COLUMN IF NOT EXISTS `reviewed_by` INT(10) UNSIGNED NULL,
  ADD COLUMN IF NOT EXISTS `reviewed_at` TIMESTAMP NULL,
  ADD COLUMN IF NOT EXISTS `admin_note` TEXT NULL,
  ADD COLUMN IF NOT EXISTS `metadata` LONGTEXT NULL;

ALTER TABLE `dispute_messages`
  ADD COLUMN IF NOT EXISTS `role` VARCHAR(50) NULL,
  ADD COLUMN IF NOT EXISTS `attachment` VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS `is_read` TINYINT(1) NOT NULL DEFAULT 0;

ALTER TABLE `api_tokens`
  ADD COLUMN IF NOT EXISTS `scopes` VARCHAR(255) DEFAULT 'read',
  ADD COLUMN IF NOT EXISTS `revoked` TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `revoked_at` TIMESTAMP NULL,
  ADD COLUMN IF NOT EXISTS `expires_at` TIMESTAMP NULL,
  ADD COLUMN IF NOT EXISTS `use_count` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS `secret_version` VARCHAR(20) DEFAULT 'v2',
  ADD COLUMN IF NOT EXISTS `secret_version_expires_at` TIMESTAMP NULL;

SET FOREIGN_KEY_CHECKS = 1;
