[program:chortke-queue]
command=php /var/www/chortke/cli.php queue:work --daemon --sleep=1 --tries=3 --max-time=0
directory=/var/www/chortke
user=www-data
numprocs=3
autostart=true
autorestart=true
startretries=10
stdout_logfile=/var/log/chortke/queue.log
stderr_logfile=/var/log/chortke/queue-error.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=5
environment=QUEUE_CONNECTION=redis
